---
- debug:
    msg: "--- {{ requested_tool }} installation ---"

#Install from role if there is one defined for the requested_tool
- name: Install {{ requested_tool }} with role method
  include_role:
    name: "{{ installable_tools[requested_tool].install_role | default(requested_tool) }}"
  when:
    - installable_tools[requested_tool].install_by_role is defined
    - installable_tools[requested_tool].install_by_role

#Otherwise, install from package
- name: Install {{ requested_tool }} with package method
  package:
    name: "{{ requested_tool }}"
    state: present
  when: installable_tools[requested_tool].install_by_role is not defined or not installable_tools[requested_tool].install_by_role